1. SELECT name FROM teams;
2. SELECT name, stadium, head_coach FROM teams WHERE conference = 'NFC';
3. SELECT head_coach FROM teams WHERE division = 'South' AND conference = 'AFC';
4. SELECT count(*) FROM players;
5. SELECT name, head_coach FROM teams WHERE division = 'North' AND conference ='NFC' OR division = 'East' AND conference = 'AFC';
6. SELECT * FROM players ORDER BY salary DESC LIMIT 50;
7. SELECT AVG(salary) FROM players;
8. SELECT name, position FROM players WHERE salary > 10000000;
9. SELECT * FROM players ORDER BY salary DESC LIMIT 1;
10. SELECT name, position FROM players ORDER BY salary ASC LIMIT 100;
11. SELECT AVG(salary) FROM players WHERE position = 'DE';
12. SELECT name FROM players WHERE team_id = (SELECT id FROM teams WHERE name = 'Buffalo Bills');
13. SELECT SUM(salary) FROM players WHERE team_id = (SELECT id FROM teams WHERE name = 'New York Giants');
14. SELECT name FROM players WHERE team_id = (SELECT id FROM teams WHERE name = 'Green Bay Packers') ORDER BY salary ASC LIMIT 1;